version: '2'

services:

  db:
    image: postgres

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - .:/Users/guido.barbaglia/.rvm/gems/ruby-2.4.4/gems
    ports:
      - '3000:3000'
    depends_on:
      - db
