default: &default
  adapter:    postgresql
  encoding:   unicode
  pool:       5
  host:       db
  username:   postgres
  password:

development:
  <<: *default
  database: hallo_rails_development

test:
  <<: *default
  database: hallo_rails_test

production:
  <<: *default
  database: hallo_rails_production
